export { Header } from "./Hero/Header";
export { Nav } from "./Hero/Nav"
export { Icons } from "./Footer/Icons"
export { Hero } from "./Hero/Hero"
export { Leaders } from "./Leaders/Leaders"
export { Eslogan } from "./Hero/Eslogan";
export { Clients } from "./Clients/Clients";
export { Soluciones } from "./Soluciones/Soluciones"
export { Calculadora } from "./Calculadora/Calculadora"
export { Perspectiva } from "./Leaders/Perspectiva"
export { Informativos } from "./Informativos/Informativos"
export { Impulsa } from "./Footer/Impulsa"
export { Footer } from "./Footer/Footer"
export { Integrales } from "./SolucionesPage/Integrales"
export { ServiciosEsp } from "./SolucionesPage/ServiciosEsp";
export { Metodologia } from "./SolucionesPage/Metodologia";
export { HeroEx } from "./ConsultoriaEmpresarial/HeroEx";
export { Method } from "./ConsultoriaEmpresarial/Method";
export { Estrategia } from "./ConsultoriaEmpresarial/Estrategia";
export { Experiencia } from "./ConsultoriaEmpresarial/Experiencia";
export { GestionPage } from "./pages/GestionPage";
export { HeroGestion } from "./GestionTributaria/HeroGestion"
export { AuditoriaPlan } from "./GestionTributaria/AuditoriaPlan";
export { EstrIm } from "./GestionTributaria/EstrIm";
export { CumplimientoNorm } from "./GestionTributaria/CumplimientoNorm";
export { OutsourcingPage } from "./pages/OutsourcingPage";
export { AuditoriaPage } from "./pages/AuditoriaPage";
export { Login } from "./login/Login";
export { HeroOutsourcing } from "./Outsourcing.tsx/HeroOutsourcing";
export { ExceOpera } from "./Outsourcing.tsx/ExceOpera";
export { ConsultoriaEje } from "./Outsourcing.tsx/ConsultoriaEje";
export { HeroAuditoria } from "./Auditoria/HeroAuditoria";
export { IntegAudit } from "./Auditoria/IntegAudit";
export { MetodologiaAud } from "./Auditoria/MetodologiaAud";
export { FaseAuditoria } from "./Auditoria/FaseAuditoria";
export { Analisis } from "./Auditoria/Analisis";
export { Crud } from "./CRUD/Crud";
export { HeroSectores } from "./Sectores/HeroSectores";
export { SectoresContainer } from "./Sectores/SectoresContainer";
export { Frase } from "./Frase";
export { SuministroPage } from "./pages/SuministroPage";
export { HeroSuministro } from "./Suministro/HeroSuministro";
export { Methodology } from "./Suministro/Methodology";
export { Estructura } from "./Suministro/Estructura";
export { FinanzasPage } from "./pages/FinanzasPage";
export { HeroFinanzas } from "./Finanzas/HeroFinanzas";
export { Operamos } from "./Finanzas/Operamos";
export { HeroMercado } from "./Mercado/HeroMercado";
export { OperamosMercado } from "./Mercado/OperamosMercado";
export { ArquitecturaEst } from "./Mercado/ArquitecturaEst";
export { HeroNovedades } from "./Novedades/HeroNovedades";
export { Filters } from "./Novedades/Filters";
export { Boletin } from "./Novedades/Boletin";
export { HeroSubNov } from "./NovedadeSub/HeroSubNov";
export { AnalisisBoletin } from "./NovedadeSub/AnalisisBoletin";
export { Descarga } from "./NovedadeSub/Descarga";
export { InfoRelaci } from "./NovedadeSub/InfoRelaci";
export { CalculadoraPage } from "./pages/CalculadoraPage";
export { HeroCalculadora } from "./Calculadora/HeroCalculadora";
export { FormCalculadora } from "./Calculadora/FormCalculadora";
export { CardCalculadora } from "./Calculadora/CardCalculadora";
export { HeroNosotros } from "./Nosotros/HeroNosotros";
export { ValoresContainer } from "./Nosotros/ValoresContainer";
export { Trayectoria } from "./Nosotros/Trayectoria";
export { Team } from "./Nosotros/Team";
export { Sede } from "./Nosotros/Sede";