export { Header } from "./Hero/Header";
export { Nav } from "./Hero/Nav"
export { Icons } from "./Footer/Icons"
export { Hero } from "./Hero/Hero"
export { Leaders } from "./Leaders/Leaders"
export { Eslogan } from "./Hero/Eslogan";
export { Clients } from "./Clients/Clients";
export { Soluciones } from "./Soluciones/Soluciones"
export { Calculadora } from "./Calculadora/Calculadora"
export { Perspectiva } from "./Leaders/Perspectiva"
export { Footer } from "./Footer/Footer"
export { Integrales } from "./SolucionesPage/Integrales"
export { ServiciosEsp } from "./SolucionesPage/ServiciosEsp";
export { Metodologia } from "./SolucionesPage/Metodologia";
export { HeroEx } from "./ConsultoriaEmpresarial/HeroEx";
export { Method } from "./ConsultoriaEmpresarial/Method";
export { Estrategia } from "./ConsultoriaEmpresarial/Estrategia";
export { Experiencia } from "./ConsultoriaEmpresarial/Experiencia";
export { GestionPage } from "./pages/GestionPage";
export { HeroGestion } from "./GestionTributaria/HeroGestion"
export { AuditoriaPlan } from "./GestionTributaria/AuditoriaPlan";
export { EstrIm } from "./GestionTributaria/EstrIm";
export { CumplimientoNorm } from "./GestionTributaria/CumplimientoNorm";
export { OutsourcingPage } from "./pages/OutsourcingPage";
export { AuditoriaPage } from "./pages/AuditoriaPage";
export { HeroOutsourcing } from "./Outsourcing.tsx/HeroOutsourcing";
export { ExceOpera } from "./Outsourcing.tsx/ExceOpera";
export { ConsultoriaEje } from "./Outsourcing.tsx/ConsultoriaEje";
export { HeroAuditoria } from "./Auditoria/HeroAuditoria";
export { IntegAudit } from "./Auditoria/IntegAudit";
export { MetodologiaAud } from "./Auditoria/MetodologiaAud";
export { FaseAuditoria } from "./Auditoria/FaseAuditoria";
export { Analisis } from "./Auditoria/Analisis";
export { HeroSectores } from "./Sectores/HeroSectores";
export { SectoresContainer } from "./Sectores/SectoresContainer";
export { Frase } from "./Frase";
export { FinancieroPage } from "./pages/FinancieroPage";
export { HeroFinanciero } from "./Financiero/HeroFinanciero";
export { Methodology } from "./Financiero/Methodology";
export { Estructura } from "./Financiero/Estructura";
export { IndustrialPage } from "./pages/IndustrialPage";
export { HeroIndustrial } from "./Finanzas/HeroIndustrial";
export { Operamos } from "./Finanzas/Operamos";
export { HeroEmpresariales } from "./Empresariales/HeroEmpresariales";
export { OperamosEmpresariales } from "./Empresariales/OperamosEmpresariales";
export { ArquitecturaEst } from "./Empresariales/ArquitecturaEst";
export { HeroNovedades } from "./Novedades/HeroNovedades";
export { Filters } from "./Novedades/Filters";
export { Boletin } from "./Novedades/Boletin";
export { HeroSubNov } from "./NovedadeSub/HeroSubNov";
export { AnalisisBoletin } from "./NovedadeSub/AnalisisBoletin";
export { Descarga } from "./NovedadeSub/Descarga";
export { InfoRelaci } from "./NovedadeSub/InfoRelaci";
export { CalculadoraPage } from "./pages/CalculadoraPage";
export { HeroCalculadora } from "./Calculadora/HeroCalculadora";
export { FormCalculadora } from "./Calculadora/FormCalculadora";
export { CardCalculadora } from "./Calculadora/CardCalculadora";
export { HeroNosotros } from "./Nosotros/HeroNosotros";
export { ValoresContainer } from "./Nosotros/ValoresContainer";
export { Trayectoria } from "./Nosotros/Trayectoria";
export { Team } from "./Nosotros/Team";
export { Sede } from "./Nosotros/Sede";
export { LogisticoPage } from "./pages/LogisticoPage";
export { HeroLogistico } from "./Logistico/HeroLogistico";
export { ArquitecturaLog } from "./Logistico/ArquitecturaLog";
export { EstrctNegocios } from "./Logistico/EstrctNegocios";
export { EstrcTributaria } from "./Sistema/EstrcTributaria";
export { HeroSistema } from "./Sistema/HeroSistema";
export { MatrizOblig } from "./Sistema/MatrizOblig";
export { PoliticasPrivacidad } from "./Politicas/PoliticasPrivacidad";
export { Terminos } from "./Terminos/Terminos";
export { PortafoliaEmpresarial } from "./ConsultoriaEmpresarial/PortafoliaEmpresarial";
export { PortafolioEstr } from "./GestionTributaria/PortafolioEstr";
export { PortafolioOutso } from "./Outsourcing.tsx/PortafolioOutso";
export { PortafolioAuditoria } from "./Auditoria/PortafolioAuditoria";
export { MembresiaPage } from "./pages/MembresiaPage";
export { HeroMembresia } from "./Membresia/HeroMembresia";
export { Banner } from "./Membresia/Banner";
export { Respaldo } from "./Membresia/Respaldo";
export { Propuesta } from "./Membresia/Propuesta";
export { ExperienciaS } from "./Membresia/ExperienciaS";
export { Alcance } from "./Membresia/Alcance";
export { PerfilIdeal } from "./Membresia/PerfilIdeal";
export { PreguntasFre } from "./Membresia/PreguntasFre";
export { Invitacion } from "./Membresia/Invitacion";